Added frequency count for boolean type columns
Quer-io/Quer.io pull request #15
Opened 2018-11-14 17:59 UTC by JaykobJ

Service/utils can now count frequency for boolean typed columns

2018-11-19 10:46 UTC, oraisa approved these changes

2018-11-19 10:47 UTC, oraisa requested changes
Needs tests

2018-12-09 10:24 UTC, JaykobJ commented
Tests added

2018-12-10 10:08 UTC, oraisa approved these changes

2018-12-10 10:08 UTC, merged